apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-classroom-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-classroom-backend
  template:
    metadata:
      labels:
        app: virtual-classroom-backend
    spec:
      containers:
      - name: virtual-classroom-backend
        image: your-backend-image-name
        ports:
        - containerPort: 3001